### PR TITLE
Improve localization launch file usability

### PR DESCRIPTION
**Pull request by davidoort**
Give users an easier way of specifying a map file that is not constrained to the smb_slam directory

### CODE REVIEW

**Comment by mantelt** [comment]
@davidoort , would you mind rebasing your changes onto the current master (and at the same time resolving the conflicts)?

**Review by mantelt — CHANGES_REQUESTED** [review]
Isn't the only thing you would like to change the localization.launch, @davidoort ?
If so, please adjust your PR accordingly...

**Comment by davidoort** [comment]
yes, when resolving conflicts I tried to accept changes from the master branch but some other changes slipped through apparently

**Comment by davidoort** [comment]
Closing this in favor of the simpler #27

**Pull request closed without merging**
