### PR TITLE
Add WaA world and fix frictionless wheels

### PR DESCRIPTION
**Pull request by daBaret**

### CODE REVIEW

**Review by davidoort — APPROVED** [review]
LGTM!

**Comment by mantelt** [comment]
@davidoort , what is not working ?

**Review by davidoort — APPROVED** [review]
Fixed a little thing in my changes, now tested again and it seems to work as usual. What was not working was robot control. I commented a line too much in the smb_standalone file which was essential for twist_mux to publish /control/smb_diff_drive/cmd_vel

**Comment by daBaret** [comment]
Closing pull request and opening https://github.com/ETHZ-RobotX/smb_common/pull/19

**Pull request closed without merging**
